const actionTypes = {
  SET_CAMERA_PERMISSION: "SET_CAMERA_PERMISSION",
  IS_QR_SCANNED: "IS_QR_SCANNED",
  UPDATE_MODAL_DATA: "UPDATE_MODAL_DATA",
  CAMERA_SHOULD_SCAN: "CAMERA_SHOULD_SCAN",
  IS_MODAL_OPEN: "IS_MODAL_OPEN",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CONTACTS: "SET_CONTACTS",
  SET_IS_SAME_QR_CODE: "SET_IS_SAME_QR_CODE",
  IS_LOADING: "IS_LOADING",
  IS_CONTACT_STARRED: "IS_CONTACT_STARRED",
};

module.exports = actionTypes;
